[project]
name = "subtitles-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncpg>=0.30.0",
    "logfire[asyncpg]>=2.11.1",
    "openai-whisper>=20240930",
    "pydantic-ai>=0.0.17",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "mypy>=1.14.1",
    "pre-commit>=4.0.1",
    "ruff>=0.8.6",
]
